name: Test, lint and deploy
on: push
jobs:
  prepare-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo data
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Save node_modules
        uses: actions/upload-artifact@v3
        with:
          name: node-modules
          path: node_modules

  test:
    runs-on: ubuntu-latest
    needs: prepare-repo
    steps:
      - name: Get repo data
        uses: actions/checkout@v3
      - name: Restore node_modules
        uses: actions/download-artifact@v3
        with:
          name: node-modules
      - name: Run tests
        run: npm run test

  lint:
    runs-on: ubuntu-latest
    needs: prepare-repo
    steps:
      - name: Get repo data
        uses: actions/checkout@v3
      - name: Restore node_modules
        uses: actions/download-artifact@v3
        with:
          name: node-modules
      - name: Run lint
        run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: prepare-repo
    steps:
      - name: Get repo data
        uses: actions/checkout@v3
      - name: Restore node_modules
        uses: actions/download-artifact@v3
        with:
          name: node-modules
      - name: Run build
        run: npm run build
      - name: Deploy
        run: echo "Deployed"
