name: Test, lint and deploy
on: push
jobs:
  prepare-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo data
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
  test:
    runs-on: ubuntu-latest
    needs: prepare-repo
    steps:
      - name: Run tests
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    needs: prepare-repo
    steps:
      - name: Run lint
        run: npm run lint
  deploy:
    runs-on: ubuntu-latest
    needs: prepare-repo
    steps:
      - name: Install deps
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Deploy
        run: echo "Deployed"
